# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Department'),
        ),
    ]
