# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 17:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20170409_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='deadline',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='project',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='worker',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 22, 17, 0, 21, 601265, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.Staff'),
        ),
        migrations.AlterField(
            model_name='task',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 22, 17, 0, 21, 602015, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='project',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.Stream'),
        ),
    ]
