# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20170822_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='task_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='task_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 9, 33, 40, 126711, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 9, 33, 40, 127410, tzinfo=utc)),
        ),
    ]
