# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 12:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_auto_20170823_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 2, 12, 29, 1, 735053, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 2, 12, 29, 1, 735943, tzinfo=utc)),
        ),
    ]
