# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 12:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_auto_20170902_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='holiday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 2, 12, 52, 25, 30964, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 2, 12, 52, 25, 31809, tzinfo=utc)),
        ),
    ]
